[package]
name = "sui-token-gen-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } 
inquire = "=0.0.7"
url = "2.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.20"
toml = "0.8.19"
chrono = "0.4.38"
regex = "1.11.1"
clap = { version = "4.5.21", features = ["derive"] }
reqwest = "0.12.9"
git2 = "0.17"
anyhow = "1.0.94"
thiserror = "2.0.4"